version: '3.7'

services:
  site: 
    image: canelrom1/mediawiki:latest
    depends_on:
      - db
    #restart: always
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  db:
    image: mariadb:latest
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "TRwC7VVxGe"
      MYSQL_DATABASE: "mediawiki"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
